[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
kobe_solana = "2jVB31Hi4MipGtC4zPxA57kf7i98j9YzvpBDRCAbELf4"




[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
